---
- name: installing and configuring filebeat
  hosts: webservers
  become: true
  tasks:

#set max_map_count
  - name: set vm.max_map_count to 262144 in sysctl
    sysctl: name={{ item.key }} value={{ item.value }}
    with_items:
      - { key: "vm.max_map_count", value: "262144" }

#download filebeat
  - name: download filebeat
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.6.2-amd64.deb

#install filebeat
  - name: install filebeat
    command: dpkg -i filebeat-7.6.2-amd64.deb

#copy to filebeat folders
  - name: copy to filebeat.yml
    copy:
     src: ./filebeat-config.yml
     dest: /etc/filebeat/filebeat.yml

#enable system
  - name: enable and configure system module
    command: filebeat modules enable system

#filebeat setup
  - name: filebeat setup
    command: filebeat setup

#start filebeat
  - name: start filebeat
    command: service filebeat start

#enable filebeat on startup
  - name: enable filebeat service
    systemd:
     name: filebeat
     enabled: yes